# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://harrykim.github.io/
baseurl: '/'
title: Harry Kim
author: Harry Kim
description: Resume & Portfolio
avatar: profile.png
email: harrykim5767@gmail.com
github: harrykim # username
# twitter: charmtham
# linkedin: username
# google_analytics: //



# needed for travis-ci build
exclude: [vendor]
